function ocr

% intializing constants


addpath('..\');

% adding a figure
	first_page=figure('name','Photo OCR',...
						'numbertitle','off',...
						'color','black',...
						'toolbar','figure',...
						'units','normalized',...
						'position',[0.15 0.15 .7 .7]);

	

% adding uipanel
	imgPanel=uipanel(first_page,...
					'units','normalized',...
					"position",[.1 .1 .8 .55],...
					'visible','off');

% adding a panel for getting image from user
	select_img_panel=uipanel(first_page,...
							'title','Image',...
							'units','normalized',...
							 "position",[.1 .75 .8 .15],...
							 'backgroundcolor','white');


% adding edit control to show the image path
	selectedImgEdit=uicontrol(select_img_panel,...
							'string','Image path here',...
							'style','edit',...
							'units','normalized',...
							"position",[0 .1 .6 .5],...
							'horizontalalignment','left');



% adding button to call stage1
	recogniseBtn=uicontrol(first_page,...
							'style','pushbutton',...
							'string','Recognise',...
							'units','normalized',...
							'position',[.4 .01 .2 .075],...
							'backgroundcolor','cyan',...
							'visible','off',...
							'callback',{@stage1,selectedImgEdit});

% adding button control to choose image
	selectImgBtn=uicontrol(select_img_panel,...
							'style','pushbutton',...
							'string','Choose Image',...
							'units','normalized',...
							'position',[.65 .1 .3 .5],...
							'backgroundcolor','cyan',...
							'callback',{@chooseImg,selectedImgEdit,imgPanel,recogniseBtn});




	imgPanel_pos=get(imgPanel,'position');

% adding axes for selected image
	ax=axes('position',imgPanel_pos,'color','black','visible','off');

	

end;